title: Marijo Vidović # your name (or website title) here
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Work experience
  <br><br>
  Associate Software Engineer
  <br><br>
  Education
  <br><br>
  Veleučilište u Rijeci / Polytechnic of Rijeka
  Bachelor's degree, Computer Systems Networking and Telecomunications
  <br><br>
  High School of Electrical Engineering and Computing
  Technician, Electrical, Electronics and Communications Engineering 
  <br><br>

  <a href="https://linkedin.com/in/marijo-vidović-243011141">View my Linked In profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
